Check if the path exists or not

diff --git a/oclint-scripts/makeWithExternClang b/oclint-scripts/makeWithExternClang
--- a/oclint-scripts/makeWithExternClang
+++ b/oclint-scripts/makeWithExternClang
@@ -7,8 +7,15 @@ if test $# -ne 1; then
     exit 1
 fi
 
+LLVM_PATH=$1
+
+if test ! -f $LLVM_PATH; then
+    echo "Could not find directory $LLVM_PATH"
+    exit 2
+fi
+
 # Build OCLint against an existing LLVM installation outside this repository.
 # The path of the LLVM build needs to be absolute.
 
-./build -llvm-root=$1 -release -clean
-./bundle -llvm-root=$1 -release -clean
+./build -llvm-root=$LLVM_PATH -release -clean
+./bundle -llvm-root=$LLVM_PATH -release -clean
